[workspace]
resolver = "2"
members = ["./lala_bar", "./notification_iced"]

[workspace.package]
version = "0.1.0"


[workspace.dependencies]
notification_iced = { version = "0.1.0", path = "notification_iced"}
futures = "0.3.30"
serde = { version = "1.0.204", features = ["derive"] }
url = "2.5.2"
zbus = { version = "4.4.0", default-features = false, features = ["tokio"] }
futures-util = "0.3.30"


